// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi9tW0A2eyifxPf1hfy3Ee8BAlKifwZQ8',
    appId: '1:133055660088:web:5dee61440d3bef8202a6cd',
    messagingSenderId: '133055660088',
    projectId: 'liftwave-6d1fe',
    authDomain: 'liftwave-6d1fe.firebaseapp.com',
    databaseURL: 'https://liftwave-6d1fe-default-rtdb.firebaseio.com',
    storageBucket: 'liftwave-6d1fe.firebasestorage.app',
    measurementId: 'G-21TN61QER8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6ve_ZDd8NcFyDIAFqTg-ECh6tAdv3ag',
    appId: '1:133055660088:android:fca92f8bd772785e02a6cd',
    messagingSenderId: '133055660088',
    projectId: 'liftwave-6d1fe',
    databaseURL: 'https://liftwave-6d1fe-default-rtdb.firebaseio.com',
    storageBucket: 'liftwave-6d1fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOLwn1tg9zeVHrMBa3efuU5XlLZEJMDnc',
    appId: '1:133055660088:ios:a274143fbf7d6ee202a6cd',
    messagingSenderId: '133055660088',
    projectId: 'liftwave-6d1fe',
    databaseURL: 'https://liftwave-6d1fe-default-rtdb.firebaseio.com',
    storageBucket: 'liftwave-6d1fe.firebasestorage.app',
    iosBundleId: 'com.liftwave.liftwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOLwn1tg9zeVHrMBa3efuU5XlLZEJMDnc',
    appId: '1:133055660088:ios:a274143fbf7d6ee202a6cd',
    messagingSenderId: '133055660088',
    projectId: 'liftwave-6d1fe',
    databaseURL: 'https://liftwave-6d1fe-default-rtdb.firebaseio.com',
    storageBucket: 'liftwave-6d1fe.firebasestorage.app',
    iosBundleId: 'com.liftwave.liftwave',
  );
}
